'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Language
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ROMEditor.UI.WPF.Language", GetType(Language).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Public Shared ReadOnly Property Add() As String
            Get
                Return ResourceManager.GetString("Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All Files.
        '''</summary>
        Public Shared ReadOnly Property AllFiles() As String
            Get
                Return ResourceManager.GetString("AllFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Author.
        '''</summary>
        Public Shared ReadOnly Property Author() As String
            Get
                Return ResourceManager.GetString("Author", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Say.
        '''</summary>
        Public Shared ReadOnly Property BasicTalk() As String
            Get
                Return ResourceManager.GetString("BasicTalk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bold Female:.
        '''</summary>
        Public Shared ReadOnly Property BoldFemale() As String
            Get
                Return ResourceManager.GetString("BoldFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bold Male:.
        '''</summary>
        Public Shared ReadOnly Property BoldMale() As String
            Get
                Return ResourceManager.GetString("BoldMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Brave Female:.
        '''</summary>
        Public Shared ReadOnly Property BraveFemale() As String
            Get
                Return ResourceManager.GetString("BraveFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Brave Male:.
        '''</summary>
        Public Shared ReadOnly Property BraveMale() As String
            Get
                Return ResourceManager.GetString("BraveMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calm Female:.
        '''</summary>
        Public Shared ReadOnly Property CalmFemale() As String
            Get
                Return ResourceManager.GetString("CalmFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Calm Male:.
        '''</summary>
        Public Shared ReadOnly Property CalmMale() As String
            Get
                Return ResourceManager.GetString("CalmMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Public Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Constants.
        '''</summary>
        Public Shared ReadOnly Property Constants() As String
            Get
                Return ResourceManager.GetString("Constants", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Public Shared ReadOnly Property Description() As String
            Get
                Return ResourceManager.GetString("Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Docile Female:.
        '''</summary>
        Public Shared ReadOnly Property DocileFemale() As String
            Get
                Return ResourceManager.GetString("DocileFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Docile Male:.
        '''</summary>
        Public Shared ReadOnly Property DocileMale() As String
            Get
                Return ResourceManager.GetString("DocileMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Public Shared ReadOnly Property English() As String
            Get
                Return ResourceManager.GetString("English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entry.
        '''</summary>
        Public Shared ReadOnly Property Entry() As String
            Get
                Return ResourceManager.GetString("Entry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to French.
        '''</summary>
        Public Shared ReadOnly Property French() As String
            Get
                Return ResourceManager.GetString("French", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game Code.
        '''</summary>
        Public Shared ReadOnly Property GameCode() As String
            Get
                Return ResourceManager.GetString("GameCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} (Loading).
        '''</summary>
        Public Shared ReadOnly Property GenericLoading() As String
            Get
                Return ResourceManager.GetString("GenericLoading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to German.
        '''</summary>
        Public Shared ReadOnly Property German() As String
            Get
                Return ResourceManager.GetString("German", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hardy Female:.
        '''</summary>
        Public Shared ReadOnly Property HardyFemale() As String
            Get
                Return ResourceManager.GetString("HardyFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hardy Male:.
        '''</summary>
        Public Shared ReadOnly Property HardyMale() As String
            Get
                Return ResourceManager.GetString("HardyMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hasty Female:.
        '''</summary>
        Public Shared ReadOnly Property HastyFemale() As String
            Get
                Return ResourceManager.GetString("HastyFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hasty Male:.
        '''</summary>
        Public Shared ReadOnly Property HastyMale() As String
            Get
                Return ResourceManager.GetString("HastyMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HTML Files.
        '''</summary>
        Public Shared ReadOnly Property HTMLFiles() As String
            Get
                Return ResourceManager.GetString("HTMLFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Public Shared ReadOnly Property ID() As String
            Get
                Return ResourceManager.GetString("ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impish Female:.
        '''</summary>
        Public Shared ReadOnly Property ImpishFemale() As String
            Get
                Return ResourceManager.GetString("ImpishFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impish Male:.
        '''</summary>
        Public Shared ReadOnly Property ImpishMale() As String
            Get
                Return ResourceManager.GetString("ImpishMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Female.
        '''</summary>
        Public Shared ReadOnly Property IsFemale() As String
            Get
                Return ResourceManager.GetString("IsFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Italian.
        '''</summary>
        Public Shared ReadOnly Property Italian() As String
            Get
                Return ResourceManager.GetString("Italian", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jolly Female:.
        '''</summary>
        Public Shared ReadOnly Property JollyFemale() As String
            Get
                Return ResourceManager.GetString("JollyFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jolly Male:.
        '''</summary>
        Public Shared ReadOnly Property JollyMale() As String
            Get
                Return ResourceManager.GetString("JollyMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lonely Female:.
        '''</summary>
        Public Shared ReadOnly Property LonelyFemale() As String
            Get
                Return ResourceManager.GetString("LonelyFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lonely Male:.
        '''</summary>
        Public Shared ReadOnly Property LonelyMale() As String
            Get
                Return ResourceManager.GetString("LonelyMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Message.
        '''</summary>
        Public Shared ReadOnly Property Message() As String
            Get
                Return ResourceManager.GetString("Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mod Info.
        '''</summary>
        Public Shared ReadOnly Property ModInfo() As String
            Get
                Return ResourceManager.GetString("ModInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mod Name.
        '''</summary>
        Public Shared ReadOnly Property ModName() As String
            Get
                Return ResourceManager.GetString("ModName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modpack Info.
        '''</summary>
        Public Shared ReadOnly Property ModpackInfo() As String
            Get
                Return ResourceManager.GetString("ModpackInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monologue.
        '''</summary>
        Public Shared ReadOnly Property Monologue() As String
            Get
                Return ResourceManager.GetString("Monologue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Naïve Female:.
        '''</summary>
        Public Shared ReadOnly Property NaiveFemale() As String
            Get
                Return ResourceManager.GetString("NaiveFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Naïve Male:.
        '''</summary>
        Public Shared ReadOnly Property NaiveMale() As String
            Get
                Return ResourceManager.GetString("NaiveMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Public Shared ReadOnly Property Name() As String
            Get
                Return ResourceManager.GetString("Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NDS ROM Files.
        '''</summary>
        Public Shared ReadOnly Property NDSRomFiles() As String
            Get
                Return ResourceManager.GetString("NDSRomFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Public Shared ReadOnly Property OK() As String
            Get
                Return ResourceManager.GetString("OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner.
        '''</summary>
        Public Shared ReadOnly Property Partner() As String
            Get
                Return ResourceManager.GetString("Partner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 01:.
        '''</summary>
        Public Shared ReadOnly Property Partner01() As String
            Get
                Return ResourceManager.GetString("Partner01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 02:.
        '''</summary>
        Public Shared ReadOnly Property Partner02() As String
            Get
                Return ResourceManager.GetString("Partner02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 03:.
        '''</summary>
        Public Shared ReadOnly Property Partner03() As String
            Get
                Return ResourceManager.GetString("Partner03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 04:.
        '''</summary>
        Public Shared ReadOnly Property Partner04() As String
            Get
                Return ResourceManager.GetString("Partner04", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 05:.
        '''</summary>
        Public Shared ReadOnly Property Partner05() As String
            Get
                Return ResourceManager.GetString("Partner05", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 06:.
        '''</summary>
        Public Shared ReadOnly Property Partner06() As String
            Get
                Return ResourceManager.GetString("Partner06", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 07:.
        '''</summary>
        Public Shared ReadOnly Property Partner07() As String
            Get
                Return ResourceManager.GetString("Partner07", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 08:.
        '''</summary>
        Public Shared ReadOnly Property Partner08() As String
            Get
                Return ResourceManager.GetString("Partner08", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 09:.
        '''</summary>
        Public Shared ReadOnly Property Partner09() As String
            Get
                Return ResourceManager.GetString("Partner09", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 10:.
        '''</summary>
        Public Shared ReadOnly Property Partner10() As String
            Get
                Return ResourceManager.GetString("Partner10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 11:.
        '''</summary>
        Public Shared ReadOnly Property Partner11() As String
            Get
                Return ResourceManager.GetString("Partner11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 12:.
        '''</summary>
        Public Shared ReadOnly Property Partner12() As String
            Get
                Return ResourceManager.GetString("Partner12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 13:.
        '''</summary>
        Public Shared ReadOnly Property Partner13() As String
            Get
                Return ResourceManager.GetString("Partner13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 14:.
        '''</summary>
        Public Shared ReadOnly Property Partner14() As String
            Get
                Return ResourceManager.GetString("Partner14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 15:.
        '''</summary>
        Public Shared ReadOnly Property Partner15() As String
            Get
                Return ResourceManager.GetString("Partner15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 16:.
        '''</summary>
        Public Shared ReadOnly Property Partner16() As String
            Get
                Return ResourceManager.GetString("Partner16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 17:.
        '''</summary>
        Public Shared ReadOnly Property Partner17() As String
            Get
                Return ResourceManager.GetString("Partner17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 18:.
        '''</summary>
        Public Shared ReadOnly Property Partner18() As String
            Get
                Return ResourceManager.GetString("Partner18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 19:.
        '''</summary>
        Public Shared ReadOnly Property Partner19() As String
            Get
                Return ResourceManager.GetString("Partner19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 20:.
        '''</summary>
        Public Shared ReadOnly Property Partner20() As String
            Get
                Return ResourceManager.GetString("Partner20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 21:.
        '''</summary>
        Public Shared ReadOnly Property Partner21() As String
            Get
                Return ResourceManager.GetString("Partner21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Partner 22:.
        '''</summary>
        Public Shared ReadOnly Property Partner22() As String
            Get
                Return ResourceManager.GetString("Partner22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Player.
        '''</summary>
        Public Shared ReadOnly Property Player() As String
            Get
                Return ResourceManager.GetString("Player", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to evandixon.
        '''</summary>
        Public Shared ReadOnly Property PluginAuthor() As String
            Get
                Return ResourceManager.GetString("PluginAuthor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rom Editor Credits:
        '''psy_commando (Pokemon portraits, most of the research)
        '''Grovyle91 (Language strings)
        '''evandixon (Personality test, bgp files).
        '''</summary>
        Public Shared ReadOnly Property PluginCredits() As String
            Get
                Return ResourceManager.GetString("PluginCredits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ROM Editor UI (WPF).
        '''</summary>
        Public Shared ReadOnly Property PluginName() As String
            Get
                Return ResourceManager.GetString("PluginName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quiet Female:.
        '''</summary>
        Public Shared ReadOnly Property QuietFemale() As String
            Get
                Return ResourceManager.GetString("QuietFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quiet Male:.
        '''</summary>
        Public Shared ReadOnly Property QuietMale() As String
            Get
                Return ResourceManager.GetString("QuietMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quirky Female:.
        '''</summary>
        Public Shared ReadOnly Property QuirkyFemale() As String
            Get
                Return ResourceManager.GetString("QuirkyFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quirky Male:.
        '''</summary>
        Public Shared ReadOnly Property QuirkyMale() As String
            Get
                Return ResourceManager.GetString("QuirkyMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rash Female:.
        '''</summary>
        Public Shared ReadOnly Property RashFemale() As String
            Get
                Return ResourceManager.GetString("RashFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rash Male:.
        '''</summary>
        Public Shared ReadOnly Property RashMale() As String
            Get
                Return ResourceManager.GetString("RashMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Relaxed Female:.
        '''</summary>
        Public Shared ReadOnly Property RelaxedFemale() As String
            Get
                Return ResourceManager.GetString("RelaxedFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Relaxed Male:.
        '''</summary>
        Public Shared ReadOnly Property RelaxedMale() As String
            Get
                Return ResourceManager.GetString("RelaxedMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ROM Selector.
        '''</summary>
        Public Shared ReadOnly Property ROMSelector() As String
            Get
                Return ResourceManager.GetString("ROMSelector", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sassy Female:.
        '''</summary>
        Public Shared ReadOnly Property SassyFemale() As String
            Get
                Return ResourceManager.GetString("SassyFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sassy Male:.
        '''</summary>
        Public Shared ReadOnly Property SassyMale() As String
            Get
                Return ResourceManager.GetString("SassyMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Script.
        '''</summary>
        Public Shared ReadOnly Property Script() As String
            Get
                Return ResourceManager.GetString("Script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Script Sort.
        '''</summary>
        Public Shared ReadOnly Property ScriptSort() As String
            Get
                Return ResourceManager.GetString("ScriptSort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search: .
        '''</summary>
        Public Shared ReadOnly Property Search() As String
            Get
                Return ResourceManager.GetString("Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Short Name.
        '''</summary>
        Public Shared ReadOnly Property ShortName() As String
            Get
                Return ResourceManager.GetString("ShortName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spanish.
        '''</summary>
        Public Shared ReadOnly Property Spanish() As String
            Get
                Return ResourceManager.GetString("Spanish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Strings.
        '''</summary>
        Public Shared ReadOnly Property Strings() As String
            Get
                Return ResourceManager.GetString("Strings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text.
        '''</summary>
        Public Shared ReadOnly Property Text() As String
            Get
                Return ResourceManager.GetString("Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3DS Build Options.
        '''</summary>
        Public Shared ReadOnly Property ThreeDSBuildOptions() As String
            Get
                Return ResourceManager.GetString("ThreeDSBuildOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Timid Female:.
        '''</summary>
        Public Shared ReadOnly Property TimidFemale() As String
            Get
                Return ResourceManager.GetString("TimidFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Timid Male:.
        '''</summary>
        Public Shared ReadOnly Property TimidMale() As String
            Get
                Return ResourceManager.GetString("TimidMale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update URL.
        '''</summary>
        Public Shared ReadOnly Property UpdateUrl() As String
            Get
                Return ResourceManager.GetString("UpdateUrl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version.
        '''</summary>
        Public Shared ReadOnly Property Version() As String
            Get
                Return ResourceManager.GetString("Version", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
