'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Reflection

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Language
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SkyEditor.SaveEditor.Language", GetType(Language).GetTypeInfo.Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DeSmuMe Save File.
        '''</summary>
        Friend Shared ReadOnly Property DeSmuMeSaveFile() As String
            Get
                Return ResourceManager.GetString("DeSmuMeSaveFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sp. Episode Held Items.
        '''</summary>
        Friend Shared ReadOnly Property EpisodeHeldItems() As String
            Get
                Return ResourceManager.GetString("EpisodeHeldItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Held Items.
        '''</summary>
        Friend Shared ReadOnly Property HeldItemsSlot() As String
            Get
                Return ResourceManager.GetString("HeldItemsSlot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Held by.
        '''</summary>
        Friend Shared ReadOnly Property ItemToStringHeldBy() As String
            Get
                Return ResourceManager.GetString("ItemToStringHeldBy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property PluginAuthor() As String
            Get
                Return ResourceManager.GetString("PluginAuthor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sky Editor Credits:
        '''evandixon (General Research)
        '''matix2267 (Pokemon Structure, code for interacting with bits)
        '''Grovyle91 (Item Structure, IDs of Pokemon/Items/etc)
        '''Prof. 9 (Team Name character encoding)
        '''Demonic722 (Misc RAM and save addresses).
        '''</summary>
        Friend Shared ReadOnly Property PluginCredits() As String
            Get
                Return ResourceManager.GetString("PluginCredits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pokémon Mystery Dungeon Save Editor.
        '''</summary>
        Friend Shared ReadOnly Property PluginName() As String
            Get
                Return ResourceManager.GetString("PluginName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raw Save File.
        '''</summary>
        Friend Shared ReadOnly Property RawSaveFile() As String
            Get
                Return ResourceManager.GetString("RawSaveFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Toolbox.
        '''</summary>
        Friend Shared ReadOnly Property RB_Toolbox() As String
            Get
                Return ResourceManager.GetString("RB_Toolbox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stored Items.
        '''</summary>
        Friend Shared ReadOnly Property StoredItemsSlot() As String
            Get
                Return ResourceManager.GetString("StoredItemsSlot", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
