'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class ListResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SaveEditor.ListResources", GetType(ListResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bulbasaur=13
        '''Charmander=8
        '''Chikorita=14
        '''Cubone=11
        '''Cyndaquil=10
        '''Eevee=2
        '''Machop=12
        '''Meowth=1
        '''Mudkip=6
        '''Pikachu=0
        '''Psyduck=7
        '''Skitty=3
        '''Squirtle=4
        '''Torchic=9
        '''Totodile=5
        '''Treeko=16.
        '''</summary>
        Public Shared ReadOnly Property RBBaseTypes() As String
            Get
                Return ResourceManager.GetString("RBBaseTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bountiful Sea: 9
        '''Treasure Sea: 10
        '''Serene Sea: 4
        '''Deep-Sea Floor: 12
        '''Deep Sea Current: 1
        '''Seafloor Cave: 1
        '''Shallow Beach: 5
        '''Mt. Deepgreen: 12
        '''Mt. Cleft: 9
        '''Mt. Moon View: 6
        '''Rainbow Peak: 1
        '''Wild Plains: 13
        '''Beau Plains: 12
        '''Sky Blue Plains: 13
        '''Safari: 15
        '''Scorched Plains: 10
        '''Sacred Field: 3
        '''Mist-Rise Forest: 14
        '''Flyaway Forest: 12
        '''Overgrown Forest: 9
        '''Energetic Forest: 15
        '''Mushroom Forest: 7
        '''Healing Forst: 1
        '''Transform Forest: 6
        '''Secretive Forest: 9
        '''Rub-a-dub River: 7
        '''Tadpole Pond: 9
        '''Turtleshe [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property RBFriendAreaOffsets() As String
            Get
                Return ResourceManager.GetString("RBFriendAreaOffsets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0=Item 0.
        '''</summary>
        Public Shared ReadOnly Property RBItemOffsets() As String
            Get
                Return ResourceManager.GetString("RBItemOffsets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beauty Scarf
        '''Def. Scarf
        '''Dodge Scarf
        '''Mobile Scarf
        '''Pass Scarf
        '''Pecha Scarf
        '''Sneak Scarf
        '''Trap Scarf
        '''Warp Scarf
        '''Bounce Scarf
        '''Diet Ribbon
        '''Friend Bow
        '''Gold Ribbon
        '''Heal Ribbon
        '''Joy Ribbon
        '''Lunar Ribbon
        '''Plain Ribbon
        '''Special Band
        '''Stamina Band
        '''Sun Ribbon
        '''Curve Band
        '''Pierce Band
        '''Power Band
        '''Weather Band
        '''Zinc Band
        '''Detect Band
        '''Munch Belt
        '''Patsy Band
        '''Persim Band
        '''Racket Band
        '''Tight Belt
        '''Twist Band
        '''No-Stick Cap
        '''Ring D
        '''Ring E
        '''Ring F
        '''Insomniscope
        '''No-Aim Scope
        '''Alert Specs
        '''Goggle Specs
        '''Lockon Spe [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property RBItemOrder() As String
            Get
                Return ResourceManager.GetString("RBItemOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0=Nothing
        '''1=Stick
        '''2=Iron Thorn
        '''3=Silver Spike
        '''4=Gold Fang
        '''5=Cacnea Spike
        '''6=Corsola Twig
        '''7=Gravelerock
        '''8=Geo Pebble
        '''9=Mobile Scarf
        '''10=Heal Ribbon
        '''11=Twist Band
        '''12=Scope Lens
        '''13=Patsy Band
        '''14=No-Stick Cap
        '''15=Pierce Band
        '''16=Joy Ribbon
        '''17=X-Ray Specs
        '''18=Persim Band
        '''19=Power Band
        '''20=Pecha Scarf
        '''21=Insomniscope
        '''22=Warp Scarf
        '''23=Tight Belt
        '''24=Sneak Scarf
        '''25=Gold Ribbon
        '''26=Goggle Specs
        '''27=Diet Ribbon
        '''28=Trap Scarf
        '''29=Racket Band
        '''30=Def. Scarf
        '''31=Stamina Band
        '''32=Plain Ribbon
        '''33=Speci [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property RBItems() As String
            Get
                Return ResourceManager.GetString("RBItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0=Tiny Woods
        '''1=Thunderwave Cave
        '''2=Mt. Steel 
        '''3=Sinister Woods 
        '''4=Silent Chasm
        '''5=Mt. Thunder 
        '''6=Mt. Thunder Peak 
        '''7=Great Canyon 
        '''8=Lapis Cave
        '''9=Mt. Blaze 
        '''10=Mt. Blaze Peak 
        '''11=Frosty Forest 
        '''12=Frosty Grotto 
        '''13=Mt. Freeze 
        '''14=Mt. Freeze Peak 
        '''15=Magma Cavern
        '''16=Magma Cavern Pit
        '''17=Sky Tower 
        '''18=Sky Tower Summit 
        '''19=Stormy Sea
        '''20=Silver Trench
        '''21=Meteor Cave
        '''22=Mt. Freeze Peak 
        '''23=Western Cave
        '''24=Boss 3
        '''25=Boss 4
        '''26=Wish Cave
        '''27=Buried Relic
        '''28=Pitfall Valley
        '''29=Northern Range  [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property RBLocations() As String
            Get
                Return ResourceManager.GetString("RBLocations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0=(Nothing)
        '''1=Iron Tail
        '''2=Ice Ball
        '''3=Yawn
        '''4=Lovely Kiss
        '''5=Nightmare
        '''6=Morning Sun
        '''7=Vital Throw
        '''8=Dig
        '''9=Thrash
        '''10=Sweet Scent
        '''11=Charm
        '''12=Rain Dance
        '''13=Confuse Ray
        '''14=Hail
        '''15=Aromatherapy
        '''16=Bubble
        '''17=Encore
        '''18=Cut
        '''19=Rage
        '''20=Super Fang
        '''21=Pain Split
        '''22=Torment
        '''23=String Shot
        '''24=Swagger
        '''25=Snore
        '''26=Heal Bell
        '''27=Screech
        '''28=Rock Throw
        '''29=Rock Smash
        '''30=Rock Slide
        '''31=Weather Ball
        '''32=Whirlpool
        '''33=Fake Tears
        '''34=Sing
        '''35=Spite
        '''36=Air Cutter
        '''37=Smokescreen
        '''38=Pursuit
        '''39=Doubles [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property RBMoves() As String
            Get
                Return ResourceManager.GetString("RBMoves", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0=??????????
        '''1=Bulbasaur
        '''2=Ivysaur
        '''3=Venusaur
        '''4=Charmander
        '''5=Charmeleon
        '''6=Charizard
        '''7=Squirtle
        '''8=Wartortle
        '''9=Blastoise
        '''10=Caterpie
        '''11=Metapod
        '''12=Butterfree
        '''13=Weedle
        '''14=Kakuna
        '''15=Beedrill
        '''16=Pidgey
        '''17=Pidgeotto
        '''18=Pidgeot
        '''19=Rattata
        '''20=Raticate
        '''21=Spearow
        '''22=Fearow
        '''23=Ekans
        '''24=Arbok
        '''25=Pikachu
        '''26=Raichu
        '''27=Sandshrew
        '''28=Sandslash
        '''29=Nidoran¾
        '''30=Nidorina
        '''31=Nidoqueen
        '''32=Nidoran½
        '''33=Nidorino
        '''34=Nidoking
        '''35=Clefairy
        '''36=Clefable
        '''37=Vulpix
        '''38=Ninetales
        '''39=Jigglypuff
        '''40=Wigg [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property RBPokemon() As String
            Get
                Return ResourceManager.GetString("RBPokemon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Player and Partner:2
        '''Special Episode:3
        '''Others:715.
        '''</summary>
        Public Shared ReadOnly Property SkyFriendAreaOffsets() As String
            Get
                Return ResourceManager.GetString("SkyFriendAreaOffsets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0=Nothing
        '''1=Stick
        '''2=Iron Thorn
        '''3=Silver Spike
        '''4=Gold Fang
        '''5=Cacnea Spike
        '''6=Corsola Twig
        '''7=Gravelerock
        '''8=Geo Pebble
        '''9=Gold Thorn
        '''10=Rare Fossil
        '''11=$$$
        '''12=$$$
        '''13=No-Slip Cap
        '''14=Y-Ray Specs
        '''15=Gaggle Specs
        '''16=Mobile Scarf
        '''17=Heal Ribbon
        '''18=Twist Band
        '''19=Scope Lens
        '''20=Patsy Band
        '''21=No-Stick Cap
        '''22=Pierce Band
        '''23=Joy Ribbon
        '''24=X-Ray Specs
        '''25=Persim Band
        '''26=Power Band
        '''27=Pecha Scarf
        '''28=Insomniscope
        '''29=Warp Scarf
        '''30=Tight Belt
        '''31=Sneak Scarf
        '''32=Gold Ribbon
        '''33=Goggle Specs
        '''34=Diet  [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property SkyItems() As String
            Get
                Return ResourceManager.GetString("SkyItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0=Test Dungeon
        '''1=Beach Cave
        '''2=Beach Cave Pit
        '''3=Drenched Bluff
        '''4=Mt. Bristle
        '''5=Mt. Bristle Peak
        '''6=Waterfall Cave
        '''7=Apple Woods
        '''8=Craggy Coast
        '''9=Side Path
        '''10=Mt. Horn
        '''11=Rock Path
        '''12=Foggy Forest
        '''13=Forest Path
        '''14=Steam Cave
        '''15=Upper Steam Cave
        '''16=Steam Cave Peak
        '''17=Amp Plains
        '''18=Far Amp Plains
        '''19=Amp Clearing
        '''20=Northern Desert
        '''21=Quicksand Cave
        '''22=Quicksand Pit
        '''23=Underground Lake
        '''24=Crystal Cave
        '''25=Crystal Crossing
        '''26=Shining Lake
        '''27=Chasm Cave
        '''28=Dark Hill
        '''29=Sealed Ruin
        '''30=D [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property SkyLocations() As String
            Get
                Return ResourceManager.GetString("SkyLocations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0=Nothing
        '''1=Iron Tail
        '''2=Ice Ball
        '''3=Yawn
        '''4=Lovely Kiss
        '''5=Nightmare
        '''6=Morning Sun
        '''7=Vital Throw
        '''8=Dig
        '''9=Thrash
        '''10=Sweet Scent
        '''11=Charm
        '''12=Rain Dance
        '''13=Confuse Ray
        '''14=Hail
        '''15=Aromatherapy
        '''16=Bubble
        '''17=Encore
        '''18=Cut
        '''19=Rage
        '''20=Super Fang
        '''21=Pain Split
        '''22=Torment
        '''23=String Shot
        '''24=Swagger
        '''25=Snore
        '''26=Heal Bell
        '''27=Screech
        '''28=Rock Throw
        '''29=Rock Smash
        '''30=Rock Slide
        '''31=Weather Ball
        '''32=Whirlpool
        '''33=Fake Tears
        '''34=Sing
        '''35=Spite
        '''36=Air Cutter
        '''37=SmokeScreen
        '''38=Pursuit
        '''39=DoubleSla [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property SkyMoves() As String
            Get
                Return ResourceManager.GetString("SkyMoves", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0=??????????
        '''1=Bulbasaur
        '''2=Ivysaur
        '''3=Venusaur
        '''4=Charmander
        '''5=Charmeleon
        '''6=Charizard
        '''7=Squirtle
        '''8=Wartortle
        '''9=Blastoise
        '''10=Caterpie
        '''11=Metapod
        '''12=Butterfree
        '''13=Weedle
        '''14=Kakuna
        '''15=Beedrill
        '''16=Pidgey
        '''17=Pidgeotto
        '''18=Pidgeot
        '''19=Rattata
        '''20=Raticate
        '''21=Spearow
        '''22=Fearow
        '''23=Ekans
        '''24=Arbok
        '''25=Pikachu
        '''26=Raichu
        '''27=Sandshrew
        '''28=Sandslash
        '''29=Nidoranｾ
        '''30=Nidorina
        '''31=Nidoqueen
        '''32=Nidoranｽ
        '''33=Nidorino
        '''34=Nidoking
        '''35=Clefairy
        '''36=Clefable
        '''37=Vulpix
        '''38=Ninetales
        '''39=Jigglypuff
        '''40=Wigg [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property SkyPokemon() As String
            Get
                Return ResourceManager.GetString("SkyPokemon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Player and Partner: 2
        '''Others:548.
        '''</summary>
        Public Shared ReadOnly Property TDFriendAreaOffsets() As String
            Get
                Return ResourceManager.GetString("TDFriendAreaOffsets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0=Nothing
        '''1=Stick
        '''2=Iron Thorn
        '''3=Silver Spike
        '''4=Gold Fang
        '''5=Cacnea Spike
        '''6=Corsola Twig
        '''7=Gravelerock
        '''8=Geo Pebble
        '''9=Gold Thorn
        '''10=Rare Fossil
        '''11=$$$
        '''12=$$$
        '''13=No-Slip Cap
        '''14=Y-Ray Specs
        '''15=Gaggle Specs
        '''16=Mobile Scarf
        '''17=Heal Ribbon
        '''18=Twist Band
        '''19=Scope Lens
        '''20=Patsy Band
        '''21=No-Stick Cap
        '''22=Pierce Band
        '''23=Joy Ribbon
        '''24=X-Ray Specs
        '''25=Persim Band
        '''26=Power Band
        '''27=Pecha Scarf
        '''28=Insomniscope
        '''29=Warp Scarf
        '''30=Tight Belt
        '''31=Sneak Scarf
        '''32=Gold Ribbon
        '''33=Goggle Specs
        '''34=Diet  [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property TDItems() As String
            Get
                Return ResourceManager.GetString("TDItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0=Test Dungeon
        '''1=Beach Cave
        '''2=Beach Cave Pit
        '''3=Drenched Bluff
        '''4=Mt. Bristle
        '''5=Mt. Bristle Peak
        '''6=Waterfall Cave
        '''7=Apple Woods
        '''8=Craggy Coast
        '''9=Side Path
        '''10=Mt. Horn
        '''11=Rock Path
        '''12=Foggy Forest
        '''13=Forest Path
        '''14=Steam Cave
        '''15=Upper Steam Cave
        '''16=Steam Cave Peak
        '''17=Amp Plains
        '''18=Far Amp Plains
        '''19=Amp Clearing
        '''20=Northern Desert
        '''21=Quicksand Cave
        '''22=Quicksand Pit
        '''23=Underground Lake
        '''24=Crystal Cave
        '''25=Crystal Crossing
        '''26=Crystal Lake
        '''27=Chasm Cave
        '''28=Dark Hill
        '''29=Sealed Ruin
        '''30=D [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property TDLocations() As String
            Get
                Return ResourceManager.GetString("TDLocations", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
