'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class FarcFilenames
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ROMEditor.FarcFilenames", GetType(FarcFilenames).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 28=wallpaper_main_perippa_01
        '''130=wallpaper_main_top01
        '''154=wallpaper_sub_skill01
        '''274=wallpaper_sub_correlation_03
        '''328=IMEV1301
        '''420=wallpaper_sub_cafe
        '''479=IMEV1302
        '''689=wallpaper_main_top02
        '''709=wallpaper_sub_bank
        '''819=wallpaper_sub_gold01
        '''999999=IMEV1303.
        '''</summary>
        Friend Shared ReadOnly Property image_2d() As String
            Get
                Return ResourceManager.GetString("image_2d", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 17097667=free_play_billboard
        '''21581661=stop@main12_090
        '''21672665=kaichuuclear1st
        '''27033494=tw03_cafe
        '''35983082=warubirunikaramareru
        '''43728358=talk_gr@main26_030
        '''64026190=honoonoshimaboss2nd
        '''69631515=talk_gr@main25_010
        '''71964523=inisienohoneatobosswin
        '''81025549=okibe_test
        '''81942789=odayaka_test
        '''82825711=rapurasutairikubin
        '''94616812=town_mid_test
        '''105235592=ev_233_01
        '''119555428=talk_gr@main25_050
        '''121208353=kyoseisave01
        '''121977251=stop@main12_010
        '''122864560=tenkeisantry1st
        '''122869575=stop@main11_120
        '''12307 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property message() As String
            Get
                Return ResourceManager.GetString("message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 17097667=free_play_billboard
        '''21581661=stop@main12_090
        '''21672665=kaichuuclear1st
        '''27033494=tw03_cafe
        '''35983082=warubirunikaramareru
        '''43728358=talk_gr@main26_030
        '''64026190=honoonoshimaboss2nd
        '''69631515=talk_gr@main25_010
        '''71964523=inisienohoneatobosswin
        '''81025549=okibe_test
        '''81942789=odayaka_test
        '''82825711=rapurasutairikubin
        '''94616812=town_mid_test
        '''105235592=ev_233_01
        '''119555428=talk_gr@main25_050
        '''121208353=kyoseisave01
        '''121977251=stop@main12_010
        '''122864560=tenkeisantry1st
        '''122869575=stop@main11_120
        '''12307 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property message_en() As String
            Get
                Return ResourceManager.GetString("message_en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 17097667=free_play_billboard
        '''21581661=stop@main12_090
        '''21672665=kaichuuclear1st
        '''27033494=tw03_cafe
        '''35983082=warubirunikaramareru
        '''43728358=talk_gr@main26_030
        '''64026190=honoonoshimaboss2nd
        '''69631515=talk_gr@main25_010
        '''71964523=inisienohoneatobosswin
        '''81025549=okibe_test
        '''81942789=odayaka_test
        '''82825711=rapurasutairikubin
        '''94616812=town_mid_test
        '''105235592=ev_233_01
        '''119555428=talk_gr@main25_050
        '''121208353=kyoseisave01
        '''121977251=stop@main12_010
        '''122864560=tenkeisantry1st
        '''122869575=stop@main11_120
        '''12307 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property message_fr() As String
            Get
                Return ResourceManager.GetString("message_fr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 17097667=free_play_billboard
        '''21581661=stop@main12_090
        '''21672665=kaichuuclear1st
        '''27033494=tw03_cafe
        '''35983082=warubirunikaramareru
        '''43728358=talk_gr@main26_030
        '''64026190=honoonoshimaboss2nd
        '''69631515=talk_gr@main25_010
        '''71964523=inisienohoneatobosswin
        '''81025549=okibe_test
        '''81942789=odayaka_test
        '''82825711=rapurasutairikubin
        '''94616812=town_mid_test
        '''105235592=ev_233_01
        '''119555428=talk_gr@main25_050
        '''121208353=kyoseisave01
        '''121977251=stop@main12_010
        '''122864560=tenkeisantry1st
        '''122869575=stop@main11_120
        '''12307 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property message_ge() As String
            Get
                Return ResourceManager.GetString("message_ge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 17097667=free_play_billboard
        '''21581661=stop@main12_090
        '''21672665=kaichuuclear1st
        '''27033494=tw03_cafe
        '''35983082=warubirunikaramareru
        '''43728358=talk_gr@main26_030
        '''64026190=honoonoshimaboss2nd
        '''69631515=talk_gr@main25_010
        '''71964523=inisienohoneatobosswin
        '''81025549=okibe_test
        '''81942789=odayaka_test
        '''82825711=rapurasutairikubin
        '''94616812=town_mid_test
        '''105235592=ev_233_01
        '''119555428=talk_gr@main25_050
        '''121208353=kyoseisave01
        '''121977251=stop@main12_010
        '''122864560=tenkeisantry1st
        '''122869575=stop@main11_120
        '''12307 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property message_it() As String
            Get
                Return ResourceManager.GetString("message_it", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 17097667=free_play_billboard
        '''21581661=stop@main12_090
        '''21672665=kaichuuclear1st
        '''27033494=tw03_cafe
        '''35983082=warubirunikaramareru
        '''43728358=talk_gr@main26_030
        '''64026190=honoonoshimaboss2nd
        '''69631515=talk_gr@main25_010
        '''71964523=inisienohoneatobosswin
        '''81025549=okibe_test
        '''81942789=odayaka_test
        '''82825711=rapurasutairikubin
        '''94616812=town_mid_test
        '''105235592=ev_233_01
        '''119555428=talk_gr@main25_050
        '''121208353=kyoseisave01
        '''121977251=stop@main12_010
        '''122864560=tenkeisantry1st
        '''122869575=stop@main11_120
        '''12307 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property message_sp() As String
            Get
                Return ResourceManager.GetString("message_sp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 17097667=free_play_billboard
        '''21581661=stop@main12_090
        '''21672665=kaichuuclear1st
        '''27033494=tw03_cafe
        '''35983082=warubirunikaramareru
        '''43728358=talk_gr@main26_030
        '''64026190=honoonoshimaboss2nd
        '''69631515=talk_gr@main25_010
        '''71964523=inisienohoneatobosswin
        '''81025549=okibe_test
        '''81942789=odayaka_test
        '''82825711=rapurasutairikubin
        '''94616812=town_mid_test
        '''105235592=ev_233_01
        '''119555428=talk_gr@main25_050
        '''121208353=kyoseisave01
        '''121977251=stop@main12_010
        '''122864560=tenkeisantry1st
        '''122869575=stop@main11_120
        '''12307 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property message_us() As String
            Get
                Return ResourceManager.GetString("message_us", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
