'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class SsbCommandNames
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ROMEditor.SsbCommandNames", GetType(SsbCommandNames).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to actraisehand.
        '''</summary>
        Friend Shared ReadOnly Property ActRaiseHand() As String
            Get
                Return ResourceManager.GetString("ActRaiseHand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fade In Background Music 2: Song: {0}, Frames: {1}, Volume: {2}.
        '''</summary>
        Friend Shared ReadOnly Property Bgm2FadeIn() As String
            Get
                Return ResourceManager.GetString("Bgm2FadeIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop Background Music 2.
        '''</summary>
        Friend Shared ReadOnly Property Bgm2Stop() As String
            Get
                Return ResourceManager.GetString("Bgm2Stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fade In Background Music 1: Song: {0}, Frames: {1}, Volume: {2}.
        '''</summary>
        Friend Shared ReadOnly Property BgmFadeIn() As String
            Get
                Return ResourceManager.GetString("BgmFadeIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop Background Music 1.
        '''</summary>
        Friend Shared ReadOnly Property BgmStop() As String
            Get
                Return ResourceManager.GetString("BgmStop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delay {0} Frames.
        '''</summary>
        Friend Shared ReadOnly Property Delay() As String
            Get
                Return ResourceManager.GetString("Delay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hide Speaker Portrait.
        '''</summary>
        Friend Shared ReadOnly Property DeletePicSpeak() As String
            Get
                Return ResourceManager.GetString("DeletePicSpeak", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to diganim?.
        '''</summary>
        Friend Shared ReadOnly Property DigAnim() As String
            Get
                Return ResourceManager.GetString("DigAnim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End Script.
        '''</summary>
        Friend Shared ReadOnly Property EndScript() As String
            Get
                Return ResourceManager.GetString("EndScript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fade In Top Background, Block: {0}, Frames: {1}.
        '''</summary>
        Friend Shared ReadOnly Property FadeInTopBg() As String
            Get
                Return ResourceManager.GetString("FadeInTopBg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fade Out Top Background, Block: {0}, Frames: {1}.
        '''</summary>
        Friend Shared ReadOnly Property FadeOutTopBg() As String
            Get
                Return ResourceManager.GetString("FadeOutTopBg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entrypoint?: Group {0}, Type {1}, Unknown {2}.
        '''</summary>
        Friend Shared ReadOnly Property GroupLabel() As String
            Get
                Return ResourceManager.GetString("GroupLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set Image Position: C:{0}, R:{1}, X:{2}, Y:{3}.
        '''</summary>
        Friend Shared ReadOnly Property ImagePos() As String
            Get
                Return ResourceManager.GetString("ImagePos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load Picture on Top Screen: {0}.
        '''</summary>
        Friend Shared ReadOnly Property LoadTopPic() As String
            Get
                Return ResourceManager.GetString("LoadTopPic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load Picture on Top Screen (Lower Layer?): {0}.
        '''</summary>
        Friend Shared ReadOnly Property LoadTopPic2() As String
            Get
                Return ResourceManager.GetString("LoadTopPic2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to maparrowclear.
        '''</summary>
        Friend Shared ReadOnly Property MapArrowClear() As String
            Get
                Return ResourceManager.GetString("MapArrowClear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to maplabelclear.
        '''</summary>
        Friend Shared ReadOnly Property MapLabelClear() As String
            Get
                Return ResourceManager.GetString("MapLabelClear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mapwaitanim.
        '''</summary>
        Friend Shared ReadOnly Property MapWaitAnim() As String
            Get
                Return ResourceManager.GetString("MapWaitAnim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Null-Op.
        '''</summary>
        Friend Shared ReadOnly Property NOP() As String
            Get
                Return ResourceManager.GetString("NOP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to norep.
        '''</summary>
        Friend Shared ReadOnly Property NoRep() As String
            Get
                Return ResourceManager.GetString("NoRep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pause Script.
        '''</summary>
        Friend Shared ReadOnly Property PauseScript() As String
            Get
                Return ResourceManager.GetString("PauseScript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Return.
        '''</summary>
        Friend Shared ReadOnly Property ReturnCommand() As String
            Get
                Return ResourceManager.GetString("ReturnCommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop Sound.
        '''</summary>
        Friend Shared ReadOnly Property SoundStop() As String
            Get
                Return ResourceManager.GetString("SoundStop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to switchparam.
        '''</summary>
        Friend Shared ReadOnly Property SwitchParam() As String
            Get
                Return ResourceManager.GetString("SwitchParam", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
