'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Language
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SaveEditor.UI.WPF.Language", GetType(Language).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Party.
        '''</summary>
        Public Shared ReadOnly Property ActivePokemonHeader() As String
            Get
                Return ResourceManager.GetString("ActivePokemonHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Public Shared ReadOnly Property Add() As String
            Get
                Return ResourceManager.GetString("Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adventures.
        '''</summary>
        Public Shared ReadOnly Property Adventures() As String
            Get
                Return ResourceManager.GetString("Adventures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attack.
        '''</summary>
        Public Shared ReadOnly Property Attack() As String
            Get
                Return ResourceManager.GetString("Attack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Base Type.
        '''</summary>
        Public Shared ReadOnly Property BaseType() As String
            Get
                Return ResourceManager.GetString("BaseType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Box Contents.
        '''</summary>
        Public Shared ReadOnly Property BoxContents() As String
            Get
                Return ResourceManager.GetString("BoxContents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current HP.
        '''</summary>
        Public Shared ReadOnly Property CurrentHP() As String
            Get
                Return ResourceManager.GetString("CurrentHP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defense.
        '''</summary>
        Public Shared ReadOnly Property Defense() As String
            Get
                Return ResourceManager.GetString("Defense", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Public Shared ReadOnly Property Delete() As String
            Get
                Return ResourceManager.GetString("Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Public Shared ReadOnly Property Edit() As String
            Get
                Return ResourceManager.GetString("Edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are holding the maximum number of items.  To add another, one must be deleted first..
        '''</summary>
        Public Shared ReadOnly Property ErrorTooManyItems() As String
            Get
                Return ResourceManager.GetString("ErrorTooManyItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exp.
        '''</summary>
        Public Shared ReadOnly Property Exp() As String
            Get
                Return ResourceManager.GetString("Exp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to General.
        '''</summary>
        Public Shared ReadOnly Property General() As String
            Get
                Return ResourceManager.GetString("General", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ginseng.
        '''</summary>
        Public Shared ReadOnly Property Ginseng() As String
            Get
                Return ResourceManager.GetString("Ginseng", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory.
        '''</summary>
        Public Shared ReadOnly Property HeldItemsTabHeader() As String
            Get
                Return ResourceManager.GetString("HeldItemsTabHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Held Money.
        '''</summary>
        Public Shared ReadOnly Property HeldMoney() As String
            Get
                Return ResourceManager.GetString("HeldMoney", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to History.
        '''</summary>
        Public Shared ReadOnly Property History() As String
            Get
                Return ResourceManager.GetString("History", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inventory.
        '''</summary>
        Public Shared ReadOnly Property Inventory() As String
            Get
                Return ResourceManager.GetString("Inventory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IQ.
        '''</summary>
        Public Shared ReadOnly Property IQ() As String
            Get
                Return ResourceManager.GetString("IQ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is Female.
        '''</summary>
        Public Shared ReadOnly Property IsFemale() As String
            Get
                Return ResourceManager.GetString("IsFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set.
        '''</summary>
        Public Shared ReadOnly Property IsSet() As String
            Get
                Return ResourceManager.GetString("IsSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level.
        '''</summary>
        Public Shared ReadOnly Property Level() As String
            Get
                Return ResourceManager.GetString("Level", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Linked.
        '''</summary>
        Public Shared ReadOnly Property Linked() As String
            Get
                Return ResourceManager.GetString("Linked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max HP.
        '''</summary>
        Public Shared ReadOnly Property MaxHP() As String
            Get
                Return ResourceManager.GetString("MaxHP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Development.
        '''</summary>
        Public Shared ReadOnly Property MenuDev() As String
            Get
                Return ResourceManager.GetString("MenuDev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Import SDF Saves.
        '''</summary>
        Public Shared ReadOnly Property MenuDevImportSDF() As String
            Get
                Return ResourceManager.GetString("MenuDevImportSDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _Open SDF.
        '''</summary>
        Public Shared ReadOnly Property MenuDevOpenSDF() As String
            Get
                Return ResourceManager.GetString("MenuDevOpenSDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Met At.
        '''</summary>
        Public Shared ReadOnly Property MetAt() As String
            Get
                Return ResourceManager.GetString("MetAt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Met Floor.
        '''</summary>
        Public Shared ReadOnly Property MetFloor() As String
            Get
                Return ResourceManager.GetString("MetFloor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Moves.
        '''</summary>
        Public Shared ReadOnly Property Moves() As String
            Get
                Return ResourceManager.GetString("Moves", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Public Shared ReadOnly Property Name() As String
            Get
                Return ResourceManager.GetString("Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Original Partner Gender.
        '''</summary>
        Public Shared ReadOnly Property OriginalPartnerGender() As String
            Get
                Return ResourceManager.GetString("OriginalPartnerGender", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Original Partner Name.
        '''</summary>
        Public Shared ReadOnly Property OriginalPartnerName() As String
            Get
                Return ResourceManager.GetString("OriginalPartnerName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Original Partner Pokémon.
        '''</summary>
        Public Shared ReadOnly Property OriginalPartnerPkm() As String
            Get
                Return ResourceManager.GetString("OriginalPartnerPkm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Original Player Gender.
        '''</summary>
        Public Shared ReadOnly Property OriginalPlayerGender() As String
            Get
                Return ResourceManager.GetString("OriginalPlayerGender", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Original Player Name.
        '''</summary>
        Public Shared ReadOnly Property OriginalPlayerName() As String
            Get
                Return ResourceManager.GetString("OriginalPlayerName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Original Player Pokémon.
        '''</summary>
        Public Shared ReadOnly Property OriginalPlayerPkm() As String
            Get
                Return ResourceManager.GetString("OriginalPlayerPkm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select your SD Card.
        '''</summary>
        Public Shared ReadOnly Property PleaseSelectSD() As String
            Get
                Return ResourceManager.GetString("PleaseSelectSD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to evandixon.
        '''</summary>
        Public Shared ReadOnly Property PluginAuthor() As String
            Get
                Return ResourceManager.GetString("PluginAuthor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sky Editor Credits:
        '''evandixon (General Research)
        '''matix2267 (Pokemon Structure, code for interacting with bits)
        '''Grovyle91 (Item Structure, IDs of Pokemon/Items/etc)
        '''Prof. 9 (Team Name character encoding)
        '''Demonic722 (Misc RAM and save addresses).
        '''</summary>
        Public Shared ReadOnly Property PluginCredits() As String
            Get
                Return ResourceManager.GetString("PluginCredits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pokémon Mystery Dungeon Save Editor.
        '''</summary>
        Public Shared ReadOnly Property PluginName() As String
            Get
                Return ResourceManager.GetString("PluginName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pokémon.
        '''</summary>
        Public Shared ReadOnly Property Pokemon() As String
            Get
                Return ResourceManager.GetString("Pokemon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PP.
        '''</summary>
        Public Shared ReadOnly Property PP() As String
            Get
                Return ResourceManager.GetString("PP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Quicksave Pokémon.
        '''</summary>
        Public Shared ReadOnly Property QuicksavePokemonTabHeader() As String
            Get
                Return ResourceManager.GetString("QuicksavePokemonTabHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rank Points.
        '''</summary>
        Public Shared ReadOnly Property RankPoints() As String
            Get
                Return ResourceManager.GetString("RankPoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rescue Points.
        '''</summary>
        Public Shared ReadOnly Property RescuePoints() As String
            Get
                Return ResourceManager.GetString("RescuePoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sealed.
        '''</summary>
        Public Shared ReadOnly Property Sealed() As String
            Get
                Return ResourceManager.GetString("Sealed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show All.
        '''</summary>
        Public Shared ReadOnly Property ShowAll() As String
            Get
                Return ResourceManager.GetString("ShowAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sp. Attack.
        '''</summary>
        Public Shared ReadOnly Property SpAttack() As String
            Get
                Return ResourceManager.GetString("SpAttack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sp. Defense.
        '''</summary>
        Public Shared ReadOnly Property SpDefense() As String
            Get
                Return ResourceManager.GetString("SpDefense", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Speed.
        '''</summary>
        Public Shared ReadOnly Property Speed() As String
            Get
                Return ResourceManager.GetString("Speed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sp. Episode Party.
        '''</summary>
        Public Shared ReadOnly Property SpEpisodeActivePokemonHeader() As String
            Get
                Return ResourceManager.GetString("SpEpisodeActivePokemonHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sp. Episode Held Money.
        '''</summary>
        Public Shared ReadOnly Property SpEpisodeHeldMoney() As String
            Get
                Return ResourceManager.GetString("SpEpisodeHeldMoney", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stored Items.
        '''</summary>
        Public Shared ReadOnly Property StoredItems() As String
            Get
                Return ResourceManager.GetString("StoredItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stored Money.
        '''</summary>
        Public Shared ReadOnly Property StoredMoney() As String
            Get
                Return ResourceManager.GetString("StoredMoney", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stored Pokémon.
        '''</summary>
        Public Shared ReadOnly Property StoredPokemonTab() As String
            Get
                Return ResourceManager.GetString("StoredPokemonTab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Switched.
        '''</summary>
        Public Shared ReadOnly Property Switched() As String
            Get
                Return ResourceManager.GetString("Switched", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Team Name.
        '''</summary>
        Public Shared ReadOnly Property TeamName() As String
            Get
                Return ResourceManager.GetString("TeamName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transformed as Female.
        '''</summary>
        Public Shared ReadOnly Property TransformedAsFemale() As String
            Get
                Return ResourceManager.GetString("TransformedAsFemale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transformed as Pokémon.
        '''</summary>
        Public Shared ReadOnly Property TransformedAsPkm() As String
            Get
                Return ResourceManager.GetString("TransformedAsPkm", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
