'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ROMEditor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 150118018
        '''781321446
        '''-1427025407
        '''-901415510
        '''-523595615
        '''663067603
        '''-487879711
        '''-478740406
        '''-93572853
        '''2023463552
        '''-157611292
        '''-789800013
        '''-75220958
        '''-245035771
        '''-376462679
        '''-1156314694
        '''974848216
        '''643055585
        '''300582488
        '''1393501584
        '''642546530
        '''-137557997
        '''-1911925550
        '''-939516080
        '''-598384997
        '''1896924932
        '''143739870
        '''1400696415
        '''-1822701762
        '''1367585910
        '''-793621678
        '''1259679618
        '''-67159027
        '''188205218
        '''1647527314
        '''607124172
        '''-389869207
        '''-55547876
        '''-148158505
        '''1146254177
        '''-1019573359
        '''-3862091
        '''797602173
        '''-2063448 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSMD_Pokemon_Name_Hashes() As String
            Get
                Return ResourceManager.GetString("PSMD_Pokemon_Name_Hashes", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
