'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Language
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SkyEditorWPF.Language", GetType(Language).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All Files.
        '''</summary>
        Public Shared ReadOnly Property AllFiles() As String
            Get
                Return ResourceManager.GetString("AllFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Background Task.
        '''</summary>
        Public Shared ReadOnly Property BackgroundTask() As String
            Get
                Return ResourceManager.GetString("BackgroundTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Build Status.
        '''</summary>
        Public Shared ReadOnly Property BuildStatus() As String
            Get
                Return ResourceManager.GetString("BuildStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create Extension.
        '''</summary>
        Public Shared ReadOnly Property CreateExtension() As String
            Get
                Return ResourceManager.GetString("CreateExtension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete this?.
        '''</summary>
        Public Shared ReadOnly Property DeleteItemConfirmation() As String
            Get
                Return ResourceManager.GetString("DeleteItemConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to close this file?  Any unsaved changes will be lost..
        '''</summary>
        Public Shared ReadOnly Property DocumentCloseConfirmation() As String
            Get
                Return ResourceManager.GetString("DocumentCloseConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Public Shared ReadOnly Property Edit() As String
            Get
                Return ResourceManager.GetString("Edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enabled.
        '''</summary>
        Public Shared ReadOnly Property Enabled() As String
            Get
                Return ResourceManager.GetString("Enabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable Development Mode.
        '''</summary>
        Public Shared ReadOnly Property EnableDevMode() As String
            Get
                Return ResourceManager.GetString("EnableDevMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable Verbose Output.
        '''</summary>
        Public Shared ReadOnly Property EnableVerboseOutput() As String
            Get
                Return ResourceManager.GetString("EnableVerboseOutput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to find file at &quot;{0}&quot;..
        '''</summary>
        Public Shared ReadOnly Property ErrorCantFindFileAt() As String
            Get
                Return ResourceManager.GetString("ErrorCantFindFileAt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to exit Sky Editor?  Any unsaved changes will be lost..
        '''</summary>
        Public Shared ReadOnly Property ExitConfirmation() As String
            Get
                Return ResourceManager.GetString("ExitConfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The provided file is not a valid extension..
        '''</summary>
        Public Shared ReadOnly Property ExtensionInstallInvalid() As String
            Get
                Return ResourceManager.GetString("ExtensionInstallInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The application must be restarted to complete installation.  Would you like to restart now?.
        '''</summary>
        Public Shared ReadOnly Property ExtensionInstallRestart() As String
            Get
                Return ResourceManager.GetString("ExtensionInstallRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extension was installed successfully..
        '''</summary>
        Public Shared ReadOnly Property ExtensionInstallSuccess() As String
            Get
                Return ResourceManager.GetString("ExtensionInstallSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown error installing extension..
        '''</summary>
        Public Shared ReadOnly Property ExtensionInstallUnknownFailure() As String
            Get
                Return ResourceManager.GetString("ExtensionInstallUnknownFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The provided extension is not supported.  This may be an extension to another extension that&apos;s not currently installed..
        '''</summary>
        Public Shared ReadOnly Property ExtensionInstallUnsupported() As String
            Get
                Return ResourceManager.GetString("ExtensionInstallUnsupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extension Manager.
        '''</summary>
        Public Shared ReadOnly Property ExtensionManager() As String
            Get
                Return ResourceManager.GetString("ExtensionManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The application must be restarted to complete uninstallation.  Would you like to restart now?.
        '''</summary>
        Public Shared ReadOnly Property ExtensionUninstallRestart() As String
            Get
                Return ResourceManager.GetString("ExtensionUninstallRestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extension was uninstalled successfully..
        '''</summary>
        Public Shared ReadOnly Property ExtensionUninstallSuccess() As String
            Get
                Return ResourceManager.GetString("ExtensionUninstallSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unknown error uninstalling extension..
        '''</summary>
        Public Shared ReadOnly Property ExtensionUninstallUnknownFailure() As String
            Get
                Return ResourceManager.GetString("ExtensionUninstallUnknownFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filename.
        '''</summary>
        Public Shared ReadOnly Property Filename() As String
            Get
                Return ResourceManager.GetString("Filename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error has occurred.  See output for details..
        '''</summary>
        Public Shared ReadOnly Property GenericErrorSeeOutput() As String
            Get
                Return ResourceManager.GetString("GenericErrorSeeOutput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Install.
        '''</summary>
        Public Shared ReadOnly Property Install() As String
            Get
                Return ResourceManager.GetString("Install", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sky Editor {0}{1}.
        '''</summary>
        Public Shared ReadOnly Property MainTitle() As String
            Get
                Return ResourceManager.GetString("MainTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is no available UI for this object of type &quot;{0}&quot;..
        '''</summary>
        Public Shared ReadOnly Property NoAvailableUI() As String
            Get
                Return ResourceManager.GetString("NoAvailableUI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Output.
        '''</summary>
        Public Shared ReadOnly Property Output() As String
            Get
                Return ResourceManager.GetString("Output", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Public Shared ReadOnly Property PluginAuthor() As String
            Get
                Return ResourceManager.GetString("PluginAuthor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Public Shared ReadOnly Property PluginCredits() As String
            Get
                Return ResourceManager.GetString("PluginCredits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sky Editor (WPF).
        '''</summary>
        Public Shared ReadOnly Property PluginName() As String
            Get
                Return ResourceManager.GetString("PluginName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plugins.
        '''</summary>
        Public Shared ReadOnly Property Plugins() As String
            Get
                Return ResourceManager.GetString("Plugins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Progress.
        '''</summary>
        Public Shared ReadOnly Property Progress() As String
            Get
                Return ResourceManager.GetString("Progress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Project Name.
        '''</summary>
        Public Shared ReadOnly Property ProjectName() As String
            Get
                Return ResourceManager.GetString("ProjectName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ready.
        '''</summary>
        Public Shared ReadOnly Property Ready() As String
            Get
                Return ResourceManager.GetString("Ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to References.
        '''</summary>
        Public Shared ReadOnly Property References() As String
            Get
                Return ResourceManager.GetString("References", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changes will not be applied until the program has been restarted..
        '''</summary>
        Public Shared ReadOnly Property SettingsApplyRestartWarning() As String
            Get
                Return ResourceManager.GetString("SettingsApplyRestartWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sky Editor Console.
        '''</summary>
        Public Shared ReadOnly Property SkyEditorConsole() As String
            Get
                Return ResourceManager.GetString("SkyEditorConsole", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sky Editor Solution.
        '''</summary>
        Public Shared ReadOnly Property SkyEditorSolution() As String
            Get
                Return ResourceManager.GetString("SkyEditorSolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to build solution.  See output for details..
        '''</summary>
        Public Shared ReadOnly Property SolutionBuildFailedSeeOutput() As String
            Get
                Return ResourceManager.GetString("SolutionBuildFailedSeeOutput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Solution Explorer.
        '''</summary>
        Public Shared ReadOnly Property SolutionExplorer() As String
            Get
                Return ResourceManager.GetString("SolutionExplorer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Public Shared ReadOnly Property Status() As String
            Get
                Return ResourceManager.GetString("Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uninstall.
        '''</summary>
        Public Shared ReadOnly Property Uninstall() As String
            Get
                Return ResourceManager.GetString("Uninstall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beta .
        '''</summary>
        Public Shared ReadOnly Property VersionBeta() As String
            Get
                Return ResourceManager.GetString("VersionBeta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome.
        '''</summary>
        Public Shared ReadOnly Property Welcome() As String
            Get
                Return ResourceManager.GetString("Welcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome to Sky Editor!  To begin, use File -&gt; Open to open a supported save file..
        '''</summary>
        Public Shared ReadOnly Property WelcomeMessage() As String
            Get
                Return ResourceManager.GetString("WelcomeMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zip Files.
        '''</summary>
        Public Shared ReadOnly Property ZipFiles() As String
            Get
                Return ResourceManager.GetString("ZipFiles", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
